topp_tracker:
  sampling_frequency: 100
  n_gridpoints: 500
  request_permission: False
  from_odom: False

  constraints:

    velocity:
      x: 5
      y: 5
      z: 5
      yaw: 2.5

    acceleration:
      x: 1.5
      y: 1.5
      z: 1.0
      yaw: 1.5
